/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ED.Tablet;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

		cppjConn conn = new cppjConn("www.yougay.com/ysql","pass",6969);

		patient gary = new patient(conn);
		patient tim = new patient(conn);

		personnel kajErSej = new personnel("6969", "nicePass69");


		

        //System.out.println(new App().getGreeting());


        
    }
}
