/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ED.Tablet;

import java.io.IOException;

import ED.Tablet.model.personnel;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;


public class App extends Application {
    public BorderPane rootLayout;
    public Stage primaryStage;
    public personnel personnel = new personnel();

    public void initRootLayout(){
        try {
            // Load root layout from fxml file.
            FXMLLoader loader = new FXMLLoader();
            loader.setLocation(App.class.getClassLoader().getResource("view/rootLayout.fxml"));
            rootLayout = (BorderPane) loader.load();
            
            // Show the scene containing the root layout.
            Scene scene = new Scene(rootLayout);
            primaryStage.setScene(scene);
            //primaryStage.setMaximized(true);
            primaryStage.show();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void showLoginView (){
        try {
            // Load loginView
            FXMLLoader loader = new FXMLLoader();
            loader.setLocation(App.class.getClassLoader().getResource("view/loginView.fxml"));
            AnchorPane loginView = (AnchorPane) loader.load();
            // Set loginView into the center of root layout.
            
            rootLayout.setCenter(loginView);
            // Give the controller access to the main app.
            ED.Tablet.controller.loginCtrl controller = loader.getController();
            controller.setMainApp(this);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void showMainView (){
        try {
            // Load mainView
            FXMLLoader loader = new FXMLLoader();
            loader.setLocation(App.class.getClassLoader().getResource("view/mainView.fxml"));
            AnchorPane mainView = (AnchorPane) loader.load();
            // Set mainView into the center of root layout.
            rootLayout.setCenter(mainView);
            // Give the controller access to the main app.
            ED.Tablet.controller.mainCtrl controller = loader.getController();
            controller.setMainApp(this);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    //Function that loads the first scene loginView, runs automatically when main() is initiated.
    //@param stage
    //@throws Exception

    public void start(Stage primaryStage){
        this.primaryStage = primaryStage;
        initRootLayout();
		showLoginView();
    }
    	
    public static void main(String[] args) {
        //Runs start() when main initiates, so that the loginView is opened
        launch(args); 
    }
}
